export const airports = {
    "0":"KBL - Kabul - Khwaja Rawash - Afghanistan",
    "1":"TIA - Tirana - Rinas - Albania",
    "2":"ALG - Algiers - Algeria",
    "3":"AAE - Annaba - Algeria",
    "4":"CZL - Constantine - Algeria",
    "5":"ORN - Oran (Ouahran) - Algeria",
    "6":"PPG - Pago Pago - American Samoa",
    "7":"ALV - Andorra La Vella H/P - Andorra",
    "8":"BUG - Bengueka - Angola",
    "9":"CAB - Cabinda - Angola",
    "10":"LAD - Luanda - 4 de Fevereiro - Angola",
    "11":"AXA - Anguilla - Anguilla",
    "12":"ANU - Antigua - Antigua",
    "13":"BUE - Buenos Aires - Argentina",
    "14":"EZE - Buenos Aires, Ezeiza Int'l Airport - Argentina",
    "15":"AEP - Buenos Aires, Jorge Newbery - Argentina",
    "16":"COR - Cordoba - Argentina",
    "17":"IGR - Iguazu, Cataratas - Argentina",
    "18":"MDQ - Mar del Plata - Argentina",
    "19":"MDZ - Mendoza - Argentina",
    "20":"ROS - Rosario - Argentina",
    "21":"SLA - Salta, Gen Belgrano - Argentina",
    "22":"BRC - San Carlos de Bariloche - Argentina",
    "23":"RSA - Santa Rosa - Argentina",
    "24":"EVN - Eriwan (Yerevan, Jerevan) - Armenia",
    "25":"AUA - Aruba - Aruba",
    "26":"ADL - Adelaide - Australia",
    "27":"ALH - Albany - Australia",
    "28":"ABX - Albury - Australia",
    "29":"ASP - Alice Springs - Australia",
    "30":"AYQ - Ayers Rock - Australia",
    "31":"AYR - Ayr - Australia",
    "32":"BNK - Ballina - Australia",
    "33":"ABM - Bamaga - Australia",
    "34":"BLT - Blackwater - Australia",
    "35":"ZBO - Bowen - Australia",
    "36":"BMP - Brampton Island - Australia",
    "37":"BNE - Brisbane - Australia",
    "38":"BHQ - Broken Hill - Australia",
    "39":"BME - Broome - Australia",
    "40":"BDB - Bundaberg - Australia",
    "41":"BWT - Burnie (Wynyard) - Australia",
    "42":"CNS - Cairns - Australia",
    "43":"CBR - Canberra - Australia",
    "44":"CVQ - Carnarvon - Australia",
    "45":"CSI - Casino - Australia",
    "46":"CED - Ceduna - Australia",
    "47":"CES - Cessnock - Australia",
    "48":"CXT - Charters Towers - Australia",
    "49":"CMQ - Clermont - Australia",
    "50":"CFS - Coffs Harbour - Australia",
    "51":"KCE - Collinsville - Australia",
    "52":"CPD - Coober Pedy - Australia",
    "53":"CTN - Cooktown - Australia",
    "54":"OOM - Cooma - Australia",
    "55":"DBY - Dalby - Australia",
    "56":"DRW - Darwin - Australia",
    "57":"DDI - Daydream Island - Australia",
    "58":"DRB - Derby - Australia",
    "59":"DPO - Devonport - Australia",
    "60":"DBO - Dubbo - Australia",
    "61":"DKI - Dunk Iceland - Australia",
    "62":"DYA - Dysart - Australia",
    "63":"EDR - Emerald - Australia",
    "64":"EMD - Emerald - Australia",
    "65":"EPR - Esperance - Australia",
    "66":"GEX - Geelong - Australia",
    "67":"GET - Geraldton - Australia",
    "68":"GLT - Gladstone - Australia",
    "69":"OOL - Gold Coast - Australia",
    "70":"GOO - Goondiwindi - Australia",
    "71":"GOV - Gove (Nhulunbuy) - Australia",
    "72":"GKL - Great Keppel Island - Australia",
    "73":"GFF - Griffith - Australia",
    "74":"GTE - Groote Eyeland - Australia",
    "75":"GTI - Groote Eylandt - Australia",
    "76":"GYP - Gympie - Australia",
    "77":"HLT - Hamilton - Australia",
    "78":"HTI - Hamilton Island - Australia",
    "79":"HIS - Hayman Island - Australia",
    "80":"HVB - Hervey Bay - Australia",
    "81":"HNK - Hinchinbrook Island - Australia",
    "82":"HBA - Hobart - Australia",
    "83":"HMH - Home Hill - Australia",
    "84":"IGH - Ingham - Australia",
    "85":"IFL - Innisfail - Australia",
    "86":"KGI - Kalgoorlie - Australia",
    "87":"KTA - Karratha - Australia",
    "88":"KRB - Karumba - Australia",
    "89":"KTR - Katherine - Australia",
    "90":"KGC - Kingscote - Australia",
    "91":"KWM - Kowanyama - Australia",
    "92":"KNX - Kununurra - Australia",
    "93":"LST - Launceston - Australia",
    "94":"LVO - Laverton - Australia",
    "95":"LEA - Learmouth (Exmouth) - Australia",
    "96":"LER - Leinster - Australia",
    "97":"LNO - Leonora - Australia",
    "98":"LDC - Lindeman Island - Australia",
    "99":"LSY - Lismore - Australia",
    "100":"LZR - Lizard Island - Australia",
    "101":"IRG - Lockhart River - Australia",
    "102":"LRE - Longreach - Australia",
    "103":"MKY - Mackay - Australia",
    "104":"MTL - Maitland - Australia",
    "105":"MBH - Maryborough - Australia",
    "106":"MKR - Meekatharra - Australia",
    "107":"MEL - Melbourne - Tullamarine - Australia",
    "108":"MIM - Merimbula - Australia",
    "109":"MMM - Middlemount - Australia",
    "110":"MQL - Mildura - Australia",
    "111":"MOV - Moranbah - Australia",
    "112":"MRZ - Moree - Australia",
    "113":"MGB - Mount Gambier - Australia",
    "114":"MMG - Mount Magnet - Australia",
    "115":"ISA - Mt. Isa - Australia",
    "116":"NAA - Narrabri - Australia",
    "117":"NRA - Narrandera - Australia",
    "118":"BEO - Newcastle - Belmont - Australia",
    "119":"NTL - Newcastle - Williamtown - Australia",
    "120":"ZNE - Newman - Australia",
    "121":"NSA - Noosa - Australia",
    "122":"NLK - Norfolk Island - Australia",
    "123":"OLP - Olympic Dam - Australia",
    "124":"OAG - Orange - Australia",
    "125":"ORS - Orpheus Island - Australia",
    "126":"PBO - Paraburdoo - Australia",
    "127":"PER - Perth Int'l - Australia",
    "128":"PUG - Port Augusta - Australia",
    "129":"PHE - Port Hedland - Australia",
    "130":"PLO - Port Lincoln - Australia",
    "131":"PQQ - Port Macquarie - Australia",
    "132":"PTJ - Portland - Australia",
    "133":"PPP - Prosperpine - Australia",
    "134":"UEE - Queenstown - Australia",
    "135":"ROK - Rockhampton - Australia",
    "136":"NSO - Scone - Australia",
    "137":"JHQ - Shute Harbour - Australia",
    "138":"SIX - Singleton - Australia",
    "139":"SOI - South Molle Island - Australia",
    "140":"KBY - Streaky Bay - Australia",
    "141":"MCY - Sunshine Coast - Australia",
    "142":"SYD - Sydney - Kingsford Smith - Australia",
    "143":"TMW - Tamworth - Australia",
    "144":"TRO - Taree - Australia",
    "145":"TEM - Temora - Australia",
    "146":"TCA - Tennant Creek - Australia",
    "147":"TIS - Thursday Island - Australia",
    "148":"TPR - Tom Price - Australia",
    "149":"TWB - Toowoomba - Australia",
    "150":"TSV - Townsville - Australia",
    "151":"WGA - Wagga - Australia",
    "152":"WMB - Warrnambool - Australia",
    "153":"WEI - Weipa - Australia",
    "154":"HAP - Whitsunday Resort - Australia",
    "155":"WYA - Whyalla - Australia",
    "156":"WHM - Wickham - Australia",
    "157":"WUN - Wiluna - Australia",
    "158":"WOL - Wollongong - Australia",
    "159":"UMR - Woomera - Australia",
    "160":"WYN - Wyndham - Australia",
    "161":"GRZ - Graz - Austria",
    "162":"INN - Innsbruck - Kranebitten - Austria",
    "163":"KLU - Klagenfurt - Austria",
    "164":"LNZ - Linz - Hoersching - Austria",
    "165":"SZG - Salzburg - W.A. Mozart - Austria",
    "166":"VIE - Wien (Vienna) - Vienna Int'l - Austria",
    "167":"BAK - Baku - Azerbaijan",
    "168":"CCZ - Chub Cay - Bahamas",
    "169":"FPO - Freeport - Bahamas",
    "170":"GHB - Govenors Harbour - Bahamas",
    "171":"GBI - Grand Bahama - Bahamas",
    "172":"MHH - Marsh Harbour - Bahamas",
    "173":"NAS - Nassau - Bahamas",
    "174":"ELH - North Eleuthera - Bahamas",
    "175":"RSD - Rock Sound - Bahamas",
    "176":"ZSA - San Salvador - Bahamas",
    "177":"TCB - Treasure Cay - Bahamas",
    "178":"BAH - Bahrain - Bahrain",
    "179":"BZL - Barisal - Bangladesh",
    "180":"CGP - Chittagong - Bangladesh",
    "181":"DAC - Dhaka - Bangladesh",
    "182":"ZYL - Sylhet - Bangladesh",
    "183":"BGI - Bridgetown, Grantley Adams Int'l - Barbados",
    "184":"MSQ - Minsk, International - Belarus",
    "185":"ANR - Antwerp - Belgium",
    "186":"BDA - Bermuda - Bermuda",
    "187":"PBH - Paro - Bhutan",
    "188":"CBB - Cochabamba - Bolivia",
    "189":"LPB - La Paz - El Alto - Bolivia",
    "190":"SRZ - Santa Cruz de la Sierra - Bolivia",
    "191":"SRB - Santa Rosa - Bolivia",
    "192":"OMO - Mostar - Bosnia and Herzegovina",
    "193":"SJJ - Sarajevo - Bosnia and Herzegovina",
    "194":"FRW - Francistown - Botswana",
    "195":"GBE - Gaborone - Botswana",
    "196":"MUB - Maun - Botswana",
    "197":"PKW - Selibi Phikwe - Botswana",
    "198":"AJU - Aracaju - Brazil",
    "199":"BEL - Belem - Brazil",
    "200":"CNF - Belo Horizonte - Brazil",
    "201":"BVB - Boa Vista - Brazil",
    "202":"BSB - Brasilia - Brazil",
    "203":"CGR - Campo Grande - Brazil",
    "204":"CGB - Cuiaba - Brazil",
    "205":"CWB - Curitiba - Brazil",
    "206":"FLN - Florianopolis - Brazil",
    "207":"FOR - Fortaleza - Brazil",
    "208":"GYN - Goiania - Brazil",
    "209":"GRU - Guarulhos Int'l - Sao Paulo - Brazil",
    "210":"JCB - Joacaba - Brazil",
    "211":"JPA - Joao Pessoa - Castro Pinto - Brazil",
    "212":"MCP - Macapa - Brazil",
    "213":"MCZ - Maceio - Brazil",
    "214":"MAO - Manaus - Brazil",
    "215":"QGF - Montenegro - Brazil",
    "216":"NAT - Natal - Brazil",
    "217":"POA - Porto Alegre - Brazil",
    "218":"PVH - Porto Velho - Brazil",
    "219":"REC - Recife - Brazil",
    "220":"RBR - Rio Branco - Brazil",
    "221":"RIO - Rio de Janeiro - Brazil",
    "222":"GIG - Rio de Janeiro - Galeao - Brazil",
    "223":"SDU - Rio de Janeiro - Santos Dumont - Brazil",
    "224":"SSA - Salvador - Brazil",
    "225":"SRA - Santa Rosa - Brazil",
    "226":"SLZ - Sao Luis - Brazil",
    "227":"SAO - Sao Paulo - Brazil",
    "228":"CGH - Sao Paulo - Congonhas - Brazil",
    "229":"GRU - Sao Paulo - Guarulhos - Brazil",
    "230":"VCP - Sao Paulo - Viracopos - Brazil",
    "231":"THE - Teresina - Brazil",
    "232":"UDI - Uberlandia, MG - Brazil",
    "233":"VIX - Vitoria - Brazil",
    "234":"BWN - Bandar Seri Begawan - Brunei",
    "235":"KUB - Kuala Belait - Brunei",
    "236":"BOJ - Bourgas/Burgas - Bulgaria",
    "237":"GOZ - Gorna - Bulgaria",
    "238":"ROU - Ruse - Bulgaria",
    "239":"SLS - Silistra - Bulgaria",
    "240":"SOF - Sofia - Vrazhdebna - Bulgaria",
    "241":"TGV - Targovishte - Bulgaria",
    "242":"VAR - Varna - Bulgaria",
    "243":"VID - Vidin - Bulgaria",
    "244":"BOY - Bobo/Dioulasso - Burkina Faso",
    "245":"OUA - Ouagadougou - Burkina Faso",
    "246":"BJM - Bujumbura - Burundi",
    "247":"PNH - Phnom Penh - Pochentong - Cambodia",
    "248":"DLA - Douala - Cameroon",
    "249":"GOU - Garoua - Cameroon",
    "250":"MVR - Maroua - Cameroon",
    "251":"NGE - N'Gaoundere - Cameroon",
    "252":"YAO - Yaounde - Cameroon",
    "253":"YAT - Attawapiskat, NT - Canada",
    "254":"YVB - Bonaventure, PQ - Canada",
    "255":"YYC - Calgary/Banff - Canada",
    "256":"YCB - Cambridge Bay - Canada",
    "257":"YYQ - Churchill - Canada",
    "258":"CFG - Cienfuegos - Canada",
    "259":"YDF - Deer Lake/Corner Brook - Canada",
    "260":"YEA - Edmonton - Canada",
    "261":"YEG - Edmonton, International - Canada",
    "262":"YXD - Edmonton, Municipal - Canada",
    "263":"YFO - Flin Flon - Canada",
    "264":"YFA - Fort Albert - Canada",
    "265":"YMM - Fort McMurray - Canada",
    "266":"YSM - Fort Smith - Canada",
    "267":"YXJ - Fort St. John - Canada",
    "268":"YFC - Fredericton - Canada",
    "269":"YQX - Gander - Canada",
    "270":"YGX - Gillam - Canada",
    "271":"YYR - Goose Bay - Canada",
    "272":"YHZ - Halifax Int'l - Canada",
    "273":"YUX - Hall Beach - Canada",
    "274":"YHM - Hamilton - Canada",
    "275":"YHR - Harrington Harbour, PQ - Canada",
    "276":"YEV - Inuvik - Canada",
    "277":"YFB - Iqaluit (Frobisher Bay) - Canada",
    "278":"ZKE - Kaschechawan, PQ - Canada",
    "279":"YLW - Kelowna, BC - Canada",
    "280":"YVP - Kuujjuaq (FortChimo) - Canada",
    "281":"YGW - Kuujjuarapik - Canada",
    "282":"YGL - La Grande - Canada",
    "283":"XLB - Lac Brochet, MB - Canada",
    "284":"YLR - Leaf Rapids - Canada",
    "285":"YXU - London - Canada",
    "286":"YQM - Moncton - Canada",
    "287":"YMQ - Montreal - Canada",
    "288":"YUL - Montreal - Dorval (Montreal-Trudeau) - Canada",
    "289":"YMX - Montreal - Mirabel - Canada",
    "290":"YSR - Nanisivik - Canada",
    "291":"YVQ - Norman Wells - Canada",
    "292":"YOW - Ottawa - Hull - Canada",
    "293":"YPN - Port Menier, PQ - Canada",
    "294":"YXS - Prince George - Canada",
    "295":"YPR - Prince Rupert/Digby Island - Canada",
    "296":"XPK - Pukatawagan - Canada",
    "297":"YQB - Quebec - Quebec Int'l - Canada",
    "298":"YOP - Rainbow Lake, AB - Canada",
    "299":"YQR - Regina - Canada",
    "300":"YRB - Resolute Bay - Canada",
    "301":"YSJ - Saint John - Canada",
    "302":"YZP - Sandspit - Canada",
    "303":"YXE - Saskatoon - Canada",
    "304":"ZTM - Shamattawa, MB - Canada",
    "305":"YYD - Smithers - Canada",
    "306":"XSI - South Indian Lake, MB - Canada",
    "307":"YIF - St. Augustin, PQ - Canada",
    "308":"YYT - St. John's - Canada",
    "309":"FSP - St. Pierre, NF - Canada",
    "310":"YXT - Terrace - Canada",
    "311":"YQD - The Pas - Canada",
    "312":"YTH - Thompson - Canada",
    "313":"YQT - Thunder Bay - Canada",
    "314":"YTO - Toronto - Canada",
    "315":"YYZ - Toronto - Lester B. Pearson - Canada",
    "316":"YTZ - Toronto Island - Canada",
    "317":"YVO - Val d'Or - Canada",
    "318":"YVR - Vancouver - Vancouver Int'l - Canada",
    "319":"YYJ - Victoria - Canada",
    "320":"YWK - Wabush - Canada",
    "321":"YXN - Whale Cove, NT - Canada",
    "322":"YXY - Whitehorse - Canada",
    "323":"YQG - Windsor Ontario - Canada",
    "324":"YWG - Winnipeg Int'l - Canada",
    "325":"YZF - Yellowknife - Canada",
    "326":"RAI - Praia - Cape Verde",
    "327":"SID - Sal - Cape Verde",
    "328":"GCM - Grand Cayman - Cayman Islands",
    "329":"BBY - Bambari - Central African Republic",
    "330":"BGU - Bangassou - Central African Republic",
    "331":"BGF - Bangui - Central African Republic",
    "332":"BBT - Berberati - Central African Republic",
    "333":"IRO - Biraro - Central African Republic",
    "334":"BIV - Bria - Central African Republic",
    "335":"CRF - Carnot - Central African Republic",
    "336":"ODA - Ouadda - Central African Republic",
    "337":"AEH - Abeche - Chad",
    "338":"MQQ - Moundou - Chad",
    "339":"NDJ - N'Djamena - Chad",
    "340":"IPC - Easter Island - Chile",
    "341":"PUQ - Punta Arenas - Chile",
    "342":"SCL - Santiago de Chile - Arturo Merino Benitez - Chile",
    "343":"VAP - Valparaiso - Chile",
    "344":"PEK - Beijing - China",
    "345":"NAY - Beijing - Nanyuan Airport - China",
    "346":"SHA - Shanghai - Hongqiao - China",
    "347":"PVG - Shanghai - Pu Dong - China",
    "348":"TSN - Tianjin - China",
    "349":"XMN - Xiamen - Fujian, China",
    "350":"DGM - Dongguan - Guangdong, China",
    "351":"CAN - Guangzhou (Canton) - Baiyun (White Cloud) - Guangdong, China",
    "352":"SZX - Shenzhen - Guangdong, China",
    "353":"NNG - Nanning - Guangxi, China",
    "354":"HRB - Harbin (Haerbin) - Heilongjiang, China",
    "355":"WUH - Wuhan - Hubei, China",
    "356":"CGQ - Changchun - Jilin, China",
    "357":"DLC - Dalian - Liaoning, China",
    "358":"SHE - Shenyang - Liaoning, China",
    "359":"MFM - Macau - Macau, China SAR",
    "360":"XIY - Xi'an - Xianyang - Shaanxi, China",
    "361":"TNA - Jinan - Shandong, China",
    "362":"TAO - Qingdao - Shandong, China",
    "363":"TYN - Taiyuan - Shanxi, China",
    "364":"CTU - Chengdu - Sichuan, China",
    "365":"CKG - Chongqing - Sichuan, China",
    "366":"URC - Urumqi - Xinjiang, China",
    "367":"HGH - Hangchow (Hangzhou) - Zhejiang, China",
    "368":"AXS - Armenia - Colombia",
    "369":"BAQ - Barranquilla - Colombia",
    "370":"BOG - Bogota - Colombia",
    "371":"BGA - Bucaramanga - Colombia",
    "372":"CLO - Cali - Colombia",
    "373":"CTG - Catagena - Colombia",
    "374":"MDE - Medellin - Colombia",
    "375":"PEI - Pereira - Colombia",
    "376":"ADZ - San Andres - Colombia",
    "377":"SSL - Santa Rosalia - Colombia",
    "378":"AJN - Anjouan - Comoros (Comores)",
    "379":"YVA - Moroni - Iconi - Comoros (Comores)",
    "380":"HAH - Moroni - Prince Said Ibrahim - Comoros (Comores)",
    "381":"BZV - Brazzaville - Congo",
    "382":"FIH - Kinshasa - N'Djili - Congo (Zaire)",
    "383":"LIQ - Lisala - Congo, Democratic Republic of The",
    "384":"RAR - Rarotonga Cook - Cook Islands",
    "385":"SJO - San Jose - Costa Rica",
    "386":"ASK - Yamoussoukro - Cote d'Ivoire (Ivory Coast)",
    "387":"LSZ - (Mali) Losinj - Losinj Arpt - Croatia (Hrvatska)",
    "388":"DBV - Dubrovnik - Croatia (Hrvatska)",
    "389":"OSI - Osijek - Croatia (Hrvatska)",
    "390":"PUY - Pula - Croatia (Hrvatska)",
    "391":"RJK - Rijeka - Croatia (Hrvatska)",
    "392":"SPU - Split - Croatia (Hrvatska)",
    "393":"ZAD - Zadar - Croatia (Hrvatska)",
    "394":"ZAG - Zagreb - Pleso - Croatia (Hrvatska)",
    "395":"HAV - Havana - Jose Marti Int'l - Cuba",
    "396":"HOG - Holguin - Cuba",
    "397":"SCU - Santiago - Antonio Maceo Airport - Cuba",
    "398":"VRA - Varadero - Cuba",
    "399":"AKT - Akrotiri - RAF - Cyprus",
    "400":"LCA - Larnaca - Cyprus",
    "401":"QLI - Limassol - Cyprus",
    "402":"NIC - Nicosia - Cyprus",
    "403":"PFO - Paphos - Cyprus",
    "404":"PRG - Prague - Ruzyne - Czech Republic",
    "405":"AAR - Aarhus - Denmark",
    "406":"AAL - Alborg - Denmark",
    "407":"BLL - Billund - Denmark",
    "408":"CPH - Copenhagen - Denmark",
    "409":"EBJ - Esbjerg - Denmark",
    "410":"FAE - Faroer - Denmark",
    "411":"KRP - Karup - Denmark",
    "412":"ODE - Odense - Denmark",
    "413":"RNN - Roenne - Denmark",
    "414":"SKS - Skrydstrup - Denmark",
    "415":"SGD - Soenderborg - Denmark",
    "416":"TED - Thisted - Denmark",
    "417":"LRM - Casa de Campo/La Romana - Dominican Republic",
    "418":"POP - Puerto Plata - Dominican Republic",
    "419":"PUJ - Punta Cana - Dominican Republic",
    "420":"SDQ - Santo Domingo - Dominican Republic",
    "421":"GYE - Guayaquil - Ecuador",
    "422":"UIO - Quito - Mariscal Sucr - Ecuador",
    "423":"SNC - Salinas - Ecuador",
    "424":"AUE - Abu Rudeis - Egypt",
    "425":"ABS - Abu Simbel - Egypt",
    "426":"AAC - Al Arish - Egypt",
    "427":"AAC - Al Arish - Egypt",
    "428":"ALY - Alexandria, El Nhouza Airport - Egypt",
    "429":"ATZ - Assiut - Egypt",
    "430":"ASW - Aswan, Daraw Airport - Egypt",
    "431":"HBH - Borg El Arab Airport - Egypt",
    "432":"CAI - Cairo Int'l - Egypt",
    "433":"EMY - El Minya - Egypt",
    "434":"HRG - Hurghada Int'l - Egypt",
    "435":"UVL - Kharga - New Valley - Egypt",
    "436":"MUH - Marsa Matrah (Marsa Matruh) - Egypt",
    "437":"UVL - New Valley - Kharga - Egypt",
    "438":"PSD - Port Said - Egypt",
    "439":"SKV - Santa Katarina - Mount Sinai - Egypt",
    "440":"SSH - Sharm El Sheikh - Egypt",
    "441":"SEW - Siwa - Egypt",
    "442":"SAL - San Salvador - El Salvador",
    "443":"SSG - Malabo - Equatorial Guinea",
    "444":"QUF - Tallinn - Pirita Harbour - Estonia",
    "445":"TLL - Tallinn - Ulemiste - Estonia",
    "446":"ADD - Addis Ababa - Ethiopia",
    "447":"NAN - Nadi - Fiji",
    "448":"SUV - Suva/Nausori - Fiji",
    "449":"SUV - Nausori - Fiji/Suva",
    "450":"ENF - Enontekioe - Finland",
    "451":"HEL - Helsinki - Vantaa - Finland",
    "452":"IVL - Ivalo - Finland",
    "453":"JOE - Joensuu - Finland",
    "454":"JYV - Jyvaeskylae - Finland",
    "455":"KAJ - Kajaani - Finland",
    "456":"KHJ - Kauhajoki - Finland",
    "457":"KEM - Kemi/Tornio - Finland",
    "458":"KTT - Kittila - Finland",
    "459":"KOK - Kokkola/Pietarsaari - Finland",
    "460":"KUO - Kuopio - Finland",
    "461":"KAO - Kuusamo - Finland",
    "462":"LPP - Lappeenranta - Finland",
    "463":"MHQ - Mariehamn (Maarianhamina) - Finland",
    "464":"MIK - Mikkeli - Finland",
    "465":"OUL - Oulu - Finland",
    "466":"POR - Pori - Finland",
    "467":"RVN - Rovaniemi - Finland",
    "468":"SVL - Savonlinna - Finland",
    "469":"SJY - Seinaejoki - Finland",
    "470":"SOT - Sodankylae - Finland",
    "471":"TMP - Tampere - Finland",
    "472":"TKU - Turku - Finland",
    "473":"VAA - Vaasa - Finland",
    "474":"VRK - Varkaus - Finland",
    "475":"AJA - Ajaccio - France",
    "476":"LBI - Albi - France",
    "477":"NCY - Annecy - France",
    "478":"AUR - Aurillac - France",
    "479":"BIA - Bastia - France",
    "480":"BIQ - Biarritz - France",
    "481":"BOD - Bordeaux - France",
    "482":"BES - Brest - France",
    "483":"CLY - Calvi - France",
    "484":"CMF - Chambery - France",
    "485":"CFE - Clermont Ferrand - France",
    "486":"DNR - Dinard - France",
    "487":"FSC - Figari - France",
    "488":"FRJ - Frejus - France",
    "489":"GNB - Grenoble - France",
    "490":"LRH - La Rochelle - France",
    "491":"LAI - Lannion - France",
    "492":"LIL - Lille - France",
    "493":"LIG - Limoges - France",
    "494":"LRT - Lorient - France",
    "495":"LDE - Lourdes/Tarbes - France",
    "496":"LYS - Lyon - France",
    "497":"MRS - Marseille - France",
    "498":"MZM - Metz - France",
    "499":"MPL - Montpellier - Frejorgues - France",
    "500":"MLH - Mulhouse - France",
    "501":"ENC - Nancy - France",
    "502":"NTE - Nantes - France",
    "503":"NCE - Nice - Cote D'Azur - France",
    "504":"FNI - Nimes - France",
    "505":"PAR - Paris - France",
    "506":"CDG - Paris - Charles de Gaulle - France",
    "507":"LBG - Paris - Le Bourget - France",
    "508":"ORY - Paris - Orly - France",
    "509":"PUF - Pau - France",
    "510":"PGF - Perpignan - France",
    "511":"UIP - Quimper - France",
    "512":"RNS - Rennes - France",
    "513":"RNE - Roanne - France",
    "514":"RDZ - Rodez - France",
    "515":"SBK - Saint Brieuc - France",
    "516":"EBU - St. Etienne - France",
    "517":"SXB - Strassburg - France",
    "518":"TLS - Toulouse - Blagnac - France",
    "519":"CAY - Cayenne - French Guayana",
    "520":"BOB - Bora Bora - French Polynesia",
    "521":"HUH - Huahine - French Polynesia",
    "522":"XMH - Manihi - French Polynesia",
    "523":"MAU - Maupiti - French Polynesia",
    "524":"MOZ - Moorea - French Polynesia",
    "525":"RFP - Raiatea - French Polynesia",
    "526":"RGI - Rangiroa - French Polynesia",
    "527":"PPT - Papeete - Faaa - French Polynesia (Tahiti)",
    "528":"LBQ - Lambarene - Gabon",
    "529":"LBV - Libreville - Gabon",
    "530":"MFF - Moanda - Gabon",
    "531":"MJL - Mouila - Gabon",
    "532":"MVB - Mvengue - Gabon",
    "533":"POG - Port Gentil - Gabon",
    "534":"UVE - Oyem - Gabon/Loyautte",
    "535":"BJL - Banjul - Gambia",
    "536":"TBS - Tbilisi - Novo Alexeyevka - Georgia",
    "537":"AGB - Augsburg - Germany",
    "538":"BYU - Bayreuth - Germany",
    "539":"BER - Berlin - Germany",
    "540":"SXF - Berlin, Schoenefeld - Germany",
    "541":"TXL - Berlin, Tegel - Germany",
    "542":"THF - Berlin, Tempelhof - Germany",
    "543":"BRE - Bremen - Germany",
    "544":"CGN - Cologne (Koeln)/Bonn - Germany",
    "545":"DTM - Dortmund - Germany",
    "546":"DRS - Dresden - Germany",
    "547":"DUS - Duesseldorf - Germany",
    "548":"ERF - Erfurt - Germany",
    "549":"HNN - Frankfurt/Hahn - Germany",
    "550":"FRA - Frankfurt/Main Int'l Airport - Germany",
    "551":"FDH - Friedrichshafen - Germany",
    "552":"HAM - Hamburg - Fuhlsbuettel - Germany",
    "553":"HAJ - Hannover - Germany",
    "554":"HOQ - Hof - Germany",
    "555":"FKB - Karlsruhe-Baden - Soellingen - Germany",
    "556":"ZNS - Kempten - Germany",
    "557":"KEL - Kiel - Holtenau - Germany",
    "558":"CGN - Koln, Koln/Bonn - Germany",
    "559":"LEJ - Leipzig - Germany",
    "560":"MUC - Muenchen (Munich) - Franz Josef Strauss - Germany",
    "561":"FMO - Muenster/Osnabrueck - Germany",
    "562":"MSR - Muenster/Osnabrueck - Germany",
    "563":"NUE - Nurnberg (Nuremberg) - Germany",
    "564":"PAD - Paderborn/Lippstadt - Germany",
    "565":"SCN - Saarbruecken - Germany",
    "566":"STR - Stuttgart - Echterdingen - Germany",
    "567":"GWT - Westerland - Germany",
    "568":"WIE - Wiesbaden, Air Base - Germany",
    "569":"ACC - Accra - Ghana",
    "570":"GIB - Gibraltar - Gibraltar",
    "571":"GPA - Araxos - Greece",
    "572":"ATH - Athens - Greece",
    "573":"HEW - Athens, Hellinikon Airport - Greece",
    "574":"CHQ - Chania - Greece",
    "575":"HER - Heraklion - Greece",
    "576":"KLX - Kalamata - Greece",
    "577":"AOK - Karpathos - Greece",
    "578":"KVA - Kavalla - Greece",
    "579":"PVK - Preveza/Lefkas - Greece",
    "580":"SKG - Saloniki - Greece",
    "581":"SMI - Samos - Greece",
    "582":"JSI - Skiathos - Greece",
    "583":"SKG - Thessaloniki - Makedonia Apt. - Greece",
    "584":"JTR - Thira - Greece",
    "585":"ZTH - Zakynthos - Greece",
    "586":"UAK - Narsarsuaq - Greenland",
    "587":"SFJ - Soendre Stroemfjord - Greenland",
    "588":"GND - Grenada - Grenada",
    "589":"PTP - Pointe a Pitre - Guadeloupe",
    "590":"SUM - Agana - Guam",
    "591":"GUM - Guam - Guam",
    "592":"GUA - Guatemala City - Guatemala",
    "593":"CKY - Conakry - Guinea",
    "594":"LEK - Labe - Guinea",
    "595":"BXO - Bissau - Guinea Bissau",
    "596":"GEO - Georgetown - Guyana",
    "597":"PAP - Port au Prince - Haiti",
    "598":"RTB - Roatan - Honduras",
    "599":"SAP - San Pedro Sula - Honduras",
    "600":"SDH - Santa Rosa Copan - Honduras",
    "601":"TGU - Tegucigalpa - Honduras",
    "602":"ZJK - Hong Kong - Chek Lap Kok - Hong Kong",
    "603":"HKG - Hong Kong - Int'l Airport (HKIA) - Hong Kong",
    "604":"BUD - Budapest, Ferihegy - Hungary",
    "605":"CXI - Christmas Line - Iceland",
    "606":"EGS - Egilsstadir - Iceland",
    "607":"KEF - Reykjavik - Keflavik International - Iceland",
    "608":"REK - Reykjavik - Metropolitan Area - Iceland",
    "609":"AMD - Ahmedabad - India",
    "610":"ATQ - Amritsar - India",
    "611":"QNB - Anand - India",
    "612":"IXB - Bagdogra - India",
    "613":"BLR - Bangalore - India",
    "614":"BDQ - Baronda - India",
    "615":"IXG - Belgaum - India",
    "616":"BHO - Bhopal - India",
    "617":"BBI - Bhubaneswar - India",
    "618":"BOM - Bombay - India",
    "619":"CCU - Calcutta (Kolkata) - Netaji Subhas Chandra - India",
    "620":"CCJ - Calicut - India",
    "621":"IXC - Chandigarh - India",
    "622":"MAA - Chennai (Madras) - India",
    "623":"COK - Cochin - India",
    "624":"CJB - Coimbatore - India",
    "625":"DEL - Delhi, Indira Gandhi - India",
    "626":"GOI - Goa - India",
    "627":"GAU - Guwahati - India",
    "628":"HYD - Hyderabad - Begumpet - India",
    "629":"JAI - Jaipur - Sanganeer - India",
    "630":"JLR - Jalandhar - India",
    "631":"IXW - Jamshedpur - Sonari - India",
    "632":"QJU - Kanpur - India",
    "633":"CCU - Kolkata (Calcutta) - Netaji Subhas Chandra - India",
    "634":"LKO - Lucknow - India",
    "635":"MAA - Madras (Chennai) - India",
    "636":"NAG - Nagpur - India",
    "637":"PAT - Patna - India",
    "638":"PNQ - Pune - India",
    "639":"RAJ - Rajkot - India",
    "640":"IXR - Ranchi - India",
    "641":"SXR - Srinagar - India",
    "642":"STV - Surat - India",
    "643":"TRV - Thiruvananthapuram - India",
    "644":"TRZ - Tiruchirapally - India",
    "645":"VNS - Varanasi - India",
    "646":"DPS - Denpasar/Bali - Indonesia",
    "647":"HLP - Jakarta - Halim Perdanakusma - Indonesia",
    "648":"JKT - Jakarta - Kemayoran - Indonesia",
    "649":"CGK - Jakarta - Soekarno-Hatta - Indonesia",
    "650":"MDC - Manado - Indonesia",
    "651":"MES - Medan - Indonesia",
    "652":"SUB - Surabaya - Juanda - Indonesia",
    "653":"TOD - Tioman - Indonesia",
    "654":"UPG - Ujung Pandang - Indonesia",
    "655":"ABD - Abadan - Iran",
    "656":"THR - Tehran (Teheran) - Mehrabad - Iran",
    "657":"BGW - Bagdad, Al Muthana - Iraq",
    "658":"SDA - Bagdad, Saddam International - Iraq",
    "659":"BSR - Basra, Basrah - Iraq",
    "660":"KIK - Kirkuk - Iraq",
    "661":"OSM - Mosul - Iraq",
    "662":"ORK - Cork - Ireland",
    "663":"DUB - Dublin - Ireland",
    "664":"GWY - Galway - Ireland",
    "665":"KIR - Kerry County - Ireland",
    "666":"NOC - Knock - Ireland",
    "667":"SNN - Shannon (Limerick) - Ireland",
    "668":"SXL - Sligo - Ireland",
    "669":"ETH - Elat - Israel",
    "670":"VDA - Elat, Ovula - Israel",
    "671":"HFA - Haifa - Israel",
    "672":"JRS - Jerusalem - Israel",
    "673":"TLV - Tel Aviv - Ben Gurion Int'l - Israel",
    "674":"AHO - Alghero Sassari - Italy",
    "675":"AOI - Ancona - Italy",
    "676":"BRI - Bari - Italy",
    "677":"BGY - Bergamo - Italy",
    "678":"BLQ - Bologna - Italy",
    "679":"VBS - Brescia, Montichiari - Italy",
    "680":"BDS - Brindisi - Italy",
    "681":"CAG - Cagliari - Italy",
    "682":"CTA - Catania - Italy",
    "683":"FLR - Florence - Italy",
    "684":"GOA - Genoa - Italy",
    "685":"SUF - Lamezia Terme - Italy",
    "686":"LMP - Lampedusa - Italy",
    "687":"MIL - Milan - Italy",
    "688":"LIN - Milan - Linate - Italy",
    "689":"MXP - Milan - Malpensa - Italy",
    "690":"BGY - Milan - Orio Al Serio - Italy",
    "691":"NAP - Naples - Italy",
    "692":"OLB - Olbia - Italy",
    "693":"PMO - Palermo - Punta Raisi - Italy",
    "694":"PNL - Pantelleria - Italy",
    "695":"PEG - Perugia - Italy",
    "696":"PSR - Pescara - Italy",
    "697":"PSA - Pisa - Gal Galilei - Italy",
    "698":"REG - Reggio Calabria - Italy",
    "699":"RMI - Rimini - Italy",
    "700":"ROM - Rome - Italy",
    "701":"CIA - Rome - Ciampino - Italy",
    "702":"FCO - Rome - Fuimicino - Italy",
    "703":"TPS - Trapani - Italy",
    "704":"TSF - Treviso - Italy",
    "705":"TRS - Trieste - Italy",
    "706":"TRN - Turin - Italy",
    "707":"VCE - Venice - Marco Polo - Italy",
    "708":"VRN - Verona - Italy",
    "709":"VBS - Verona (Brescia) Montichiari - Italy",
    "710":"ABJ - Abidjan - Ivory Coast",
    "711":"BYK - Bouake - Ivory Coast",
    "712":"DJO - Daloa - Ivory Coast",
    "713":"HGO - Korhogo - Ivory Coast",
    "714":"MJC - Man - Ivory Coast",
    "715":"SPY - San Pedro - Ivory Coast",
    "716":"ZSS - Sassandra - Ivory Coast",
    "717":"KIN - Kingston - Norman Manley - Jamaica",
    "718":"MBJ - Montenego Bay - Jamaica",
    "719":"AXT - Akita - Japan",
    "720":"ASJ - Amami - Japan",
    "721":"AOJ - Aomori - Japan",
    "722":"QCB - Chiba City - Japan",
    "723":"CTS - Chitose - Japan",
    "724":"FUK - Fukuoka - Japan",
    "725":"FKS - Fukushima-shi, Fukushima Airport - Japan",
    "726":"HAC - Hachijo Jima - Japan",
    "727":"HKD - Hakodate - Japan",
    "728":"HIJ - Hiroshima International - Japan",
    "729":"LSG - Ishigaki - Japan",
    "730":"KOJ - Kagoshima - Japan",
    "731":"UKB - Kobe - Japan",
    "732":"KCZ - Kochi - Japan",
    "733":"KMQ - Komatsu - Japan",
    "734":"KMJ - Kumamoto - Japan",
    "735":"KUH - Kushiro - Japan",
    "736":"UKY - Kyoto - Japan",
    "737":"MMJ - Matsumoto, Nagano - Japan",
    "738":"MYJ - Matsuyama - Japan",
    "739":"MMY - Miyako Jima (Ryuku Islands) - Hirara - Japan",
    "740":"KMI - Miyazaki - Japan",
    "741":"HNA - Morioka, Hanamaki - Japan",
    "742":"NGS - Nagasaki - Japan",
    "743":"NGO - Nagoya - Komaki AFB - Japan",
    "744":"KIJ - Niigata - Japan",
    "745":"OIT - Oita - Japan",
    "746":"OKJ - Okayama - Japan",
    "747":"OKA - Okinawa, Ryukyo Island - Naha - Japan",
    "748":"ITM - Osaka - Itami - Japan",
    "749":"KIX - Osaka - Kansai Int'l Airport - Japan",
    "750":"OSA - Osaka, Metropolitan Area - Japan",
    "751":"SDS - Sado Shima - Japan",
    "752":"OKD - Sapporo - Okadama - Hokkaido, Japan",
    "753":"SPK - Sapporo - Hokkaido, Japan",
    "754":"CTS - Sapporo - Shin-Chitose Airport - Japan",
    "755":"SDJ - Sendai - Japan",
    "756":"TAK - Takamatsu - Japan",
    "757":"TKS - Tokushima - Japan",
    "758":"TYO - Tokyo - Japan",
    "759":"HND - Tokyo - Haneda - Japan",
    "760":"NRT - Tokyo - Narita - Japan",
    "761":"TOY - Toyama - Japan",
    "762":"GAJ - Yamagata, Junmachi - Japan",
    "763":"YOK - Yokohama - Japan",
    "764":"ADJ - Amman, Civil - Marka Airport - Jordan",
    "765":"AMM - Amman, Queen Alia Intl - Jordan",
    "766":"AQJ - Aqaba - Jordan",
    "767":"ADX - Aktyubinsk - Kazakhstan",
    "768":"ALA - Alma Ata - Kazakhstan",
    "769":"TSE - Astana - Kazakstan",
    "770":"MYD - Malindi - Kenya",
    "771":"MBA - Mombasa - Moi International - Kenya",
    "772":"NBO - Nairobi - Kenya",
    "773":"KNS - King Island - King Island",
    "774":"KWI - Kuwait - Kuwait Int'l - Kuwait",
    "775":"VTE - Vientiane - Wattay - Laos",
    "776":"RIX - Riga - Latvia",
    "777":"BEY - Beirut - Lebanon",
    "778":"GJN - Jounieh - Lebanon",
    "779":"MSU - Maseru - Moshoeshoe Int'l - Lesotho",
    "780":"MLW - Monrovia - Liberia",
    "781":"ROB - Monrovia - Roberts Int'l - Liberia",
    "782":"BEN - Bengasi - Libya",
    "783":"SEB - Sehba - Libya",
    "784":"TIP - Tripoli - Tripoli Int'l - Libya",
    "785":"VNO - Wilna (Vilnius) - Lithuania",
    "786":"OHD - Ohrid - Macedonia",
    "787":"SKP - Skopje - Macedonia",
    "788":"TNR - Antananarivo (Tanannarive) - Madagascar",
    "789":"MJN - Majunga - Madagascar",
    "790":"BLZ - Blantyre - Malawi",
    "791":"LLW - Lilongwe - Lilongwe International - Malawi",
    "792":"BTU - Bintulu - Malaysia",
    "793":"JHB - Johore Bahru - Malaysia",
    "794":"BKI - Kota Kinabalu - Malaysia",
    "795":"KUL - Kuala Lumpur - Int'l Airport - Malaysia",
    "796":"SZB - Kuala Lumpur - Sultan Abdul Aziz Shah - Malaysia",
    "797":"KUA - Kuantan - Malaysia",
    "798":"KCH - Kuching - Malaysia",
    "799":"LBU - Labuan - Malaysia",
    "800":"LGK - Langkawi - Malaysia",
    "801":"MYY - Miri - Malaysia",
    "802":"PEN - Penang International - Malaysia",
    "803":"SBW - Sibu - Malaysia",
    "804":"TWU - Tawau - Malaysia",
    "805":"MLE - Male - International - Maledives",
    "806":"BKO - Bamako - Mali",
    "807":"MLA - Luga - Malta",
    "808":"FDF - Fort de France - Martinique",
    "809":"NDB - Nouadhibou - Mauritania",
    "810":"NKC - Nouakchott - Mauritania",
    "811":"OUZ - Zouerate - Mauritania",
    "812":"MRU - Mauritius - S.Seewoosagur Ram Int'l - Mauritius",
    "813":"RRG - Rodrigues Island - Mauritius",
    "814":"DZA - Dzaoudzi - Mayotte",
    "815":"ACA - Acapulco - Mexico",
    "816":"AGU - Aguascaliente - Mexico",
    "817":"CUN - Cancun - Mexico",
    "818":"CZA - Chichen Itza - Mexico",
    "819":"CUU - Chihuahua, Gen Fierro Villalobos - Mexico",
    "820":"CME - Ciudad Del Carmen - Mexico",
    "821":"CJS - Ciudad Juarez - Mexico",
    "822":"CEN - Ciudad Obregon - Mexico",
    "823":"CVM - Ciudad Victoria - Mexico",
    "824":"CLQ - Colima - Mexico",
    "825":"CUL - Culiacan - Mexico",
    "826":"GDL - Guadalajara - Mexico",
    "827":"HMO - Hermosillo - Gen. Pesqueira Garcia - Mexico",
    "828":"HUX - Huatulco - Mexico",
    "829":"ZIH - Ixtapa/Zihuatenejo - Mexico",
    "830":"LAP - La Paz - Leon - Mexico",
    "831":"LZC - Lazaro Cardenas - Mexico",
    "832":"SJD - Los Cabos - Mexico",
    "833":"ZLO - Manzanillo - Mexico",
    "834":"MZT - Mazatlan - Mexico",
    "835":"MID - Merida - Mexico",
    "836":"MXL - Mexicali - Mexico",
    "837":"MEX - Mexico City - Juarez International - Mexico",
    "838":"MTT - Minatitlan - Mexico",
    "839":"NTR - Monterrey - Aeropuerto Del Norte - Mexico",
    "840":"MLM - Morelia - Mexico",
    "841":"NLD - Nuevo Laredo - Mexico",
    "842":"OAX - Oaxaca - Mexico",
    "843":"PBC - Puebla - Mexico",
    "844":"PVR - Puerto Vallarta - Mexico",
    "845":"SJD - San Jose Cabo - Mexico",
    "846":"SLP - San Luis Potosi - Mexico",
    "847":"SRL - Santa Rosalia - Mexico",
    "848":"TAM - Tampico - Gen. F. Javier Mina - Mexico",
    "849":"TIJ - Tijuana - Rodriguez - Mexico",
    "850":"TGZ - Tuxtla Gutierrez - Mexico",
    "851":"VER - Veracruz - Mexico",
    "852":"VSA - Villahermosa - Mexico",
    "853":"ZCL - Zacatecas - Mexico",
    "854":"PNI - Pohnpei - Micronesia",
    "855":"ULN - Ulaanbaatar - Buyant Uhaa - Mongolia",
    "856":"AGA - Agadir - Morocco",
    "857":"AHU - Al Hoceima - Morocco",
    "858":"CAS - Casablanca - Morocco",
    "859":"CMN - Casablanca, Mohamed V - Morocco",
    "860":"RAK - Marrakech - Menara - Morocco",
    "861":"OZZ - Ouarzazate - Morocco",
    "862":"OUD - Oujda - Morocco",
    "863":"RBA - Rabat - Sale - Morocco",
    "864":"TNG - Tanger - Boukhalef - Morocco",
    "865":"BEW - Beira - Mozambique",
    "866":"MPM - Maputo - Maputo International - Mozambique",
    "867":"RGN - Rangoon (Yangon) - Mingaladon - Myanmar (Burma)",
    "868":"RGN - Yangon (Rangoon) - Mingaladon - Myanmar (Burma)",
    "869":"MPA - Katima Mulilo/Mpacha - Namibia",
    "870":"KMP - Keetmanshoop - Namibia",
    "871":"LUD - Luederitz - Namibia",
    "872":"OKU - Mokuti - Namibia",
    "873":"OND - Ondangwa - Namibia",
    "874":"OMD - Oranjemund - Namibia",
    "875":"NDU - Rundu - Namibia",
    "876":"SWP - Swakopmund - Namibia",
    "877":"TSB - Tsumeb - Namibia",
    "878":"ERS - Windhoek - Eros - Namibia",
    "879":"WDH - Windhoek - Hosea Kutako Int'l - Namibia",
    "880":"KTM - Kathmandu - Tribhuvan - Nepal",
    "881":"AMS - Amsterdam, Schiphol - Netherlands",
    "882":"HAG - Den Haag (The Hague) - Netherlands",
    "883":"EIN - Eindhoven - Netherlands",
    "884":"LEY - Lelystad - Netherlands",
    "885":"MST - Maastricht/Aachen - Netherlands",
    "886":"RTM - Rotterdam - Netherlands",
    "887":"BON - Bonaire - Netherlands Antilles",
    "888":"CUR - Curacao - Netherlands Antilles",
    "889":"SXM - St. Marteen - Netherlands Antilles",
    "890":"ILP - Ile des Pins - New Caledonia",
    "891":"IOU - Ile Ouen - New Caledonia",
    "892":"MEE - Mare - New Caledonia",
    "893":"NOU - Noumea - New Caledonia",
    "894":"TOU - Touho - New Caledonia",
    "895":"AKL - Auckland - New Zealand",
    "896":"BHE - Blenheim - New Zealand",
    "897":"CHC - Christchurch - New Zealand",
    "898":"DUD - Dunedin - New Zealand",
    "899":"IVC - Incercargill - New Zealand",
    "900":"IVC - Invercargill - New Zealand",
    "901":"MFN - Milford Sound - New Zealand",
    "902":"GTN - Mount Cook - New Zealand",
    "903":"NSN - Nelson - New Zealand",
    "904":"PMR - Palmerston North - New Zealand",
    "905":"ZQN - Queenstown - New Zealand",
    "906":"ROT - Rotorua - New Zealand",
    "907":"TEU - Te Anau - New Zealand",
    "908":"WLG - Wellington - New Zealand",
    "909":"WHK - Whakatane - New Zealand",
    "910":"WRE - Whangarei - New Zealand",
    "911":"MGA - Managua - Augusto C Sandino - Nicaragua",
    "912":"AJY - Agades - Niger",
    "913":"RLT - Arlit - Niger",
    "914":"MFQ - Maradi - Niger",
    "915":"NIM - Niamey - Niger",
    "916":"ABV - Abuja International - Nigeria",
    "917":"KAN - Kano - Nigeria",
    "918":"LOS - Lagos - Murtala Muhammed - Nigeria",
    "919":"PHC - Port Harcourt - Nigeria",
    "920":"FNJ - Pyongyang - Sunan - North Korea",
    "921":"SPN - Saipan - Northern Mariana Islands",
    "922":"AES - Alesund - Norway",
    "923":"ALF - Alta - Norway",
    "924":"BDU - Bardufoss - Norway",
    "925":"BGO - Bergen - Norway",
    "926":"BOO - Bodo - Norway",
    "927":"BNN - Broennoeysund - Norway",
    "928":"EVE - Evenes - Norway",
    "929":"FRO - Floro - Norway",
    "930":"HFT - Hammerfest - Norway",
    "931":"HAU - Haugesund - Norway",
    "932":"KKN - Kirkenes - Norway",
    "933":"KRS - Kristiansand - Norway",
    "934":"KSU - Kristiansund - Norway",
    "935":"LKL - Lakselv - Norway",
    "936":"OSL - Oslo - Norway",
    "937":"FBU - Oslo - Fornebu - Norway",
    "938":"TRF - Oslo - Sandefjord - Norway",
    "939":"SOG - Sogndal - Norway",
    "940":"SVG - Stavanger - Norway",
    "941":"TOS - Tromsoe - Norway",
    "942":"TRD - Trondheim - Norway",
    "943":"LYR - Longyearbyen - Svalbard - Svalbard/Norway",
    "944":"MCT - Muscat - Seeb - Oman",
    "945":"SLL - Salalah - Oman",
    "946":"BHV - Bahawalpur - Pakistan",
    "947":"BNP - Bannu - Pakistan",
    "948":"CJL - Chitral - Pakistan",
    "949":"DSK - Dera Ismail Khan - Pakistan",
    "950":"LYP - Faisalabad - Pakistan",
    "951":"GIL - Gilgit - Pakistan",
    "952":"GWD - Gwadar - Pakistan",
    "953":"HDD - Hyderabad - Pakistan",
    "954":"ISB - Islamabad - Islamabad Int'l - Pakistan",
    "955":"JAG - Jacobabad - Pakistan",
    "956":"JIW - Jiwani - Pakistan",
    "957":"KHI - Karachi - Quaid-E-Azam Int'l - Pakistan",
    "958":"KDD - Khuzdar - Pakistan",
    "959":"OHT - Kohat - Pakistan",
    "960":"LHE - Lahore - Pakistan",
    "961":"MWD - Mianwali - Pakistan",
    "962":"QML - Mirpur - Pakistan",
    "963":"MJD - Moenjodaro - Pakistan",
    "964":"MUX - Multan - Pakistan",
    "965":"MFG - Muzaffarabad - Pakistan",
    "966":"WNS - Nawab Shah - Pakistan",
    "967":"PJG - Panjgur - Pakistan",
    "968":"PSI - Pasni - Pakistan",
    "969":"PEW - Peshawar - Pakistan",
    "970":"UET - Quetta - Pakistan",
    "971":"RYK - Rahim Yar Khan - Pakistan",
    "972":"RAZ - Rawala Kot - Pakistan",
    "973":"RWP - Rawalpindi - Pakistan",
    "974":"SDT - Saidu Sharif - Pakistan",
    "975":"MPD - Sindhri - Pakistan",
    "976":"KDU - Skardu - Pakistan",
    "977":"SUL - Sui - Pakistan",
    "978":"SKZ - Sukkur - Pakistan",
    "979":"TUK - Turbat - Pakistan",
    "980":"PZH - Zhob - Pakistan",
    "981":"PTY - Panama City - Tocumen International - Panama",
    "982":"LAE - Lae - Papua New Guinea",
    "983":"MFO - Manguna - Papua New Guinea",
    "984":"POM - Port Moresby - Jackson Field - Papua New Guinea",
    "985":"ASU - Asuncion - Paraguay",
    "986":"LIF - Lifou - Loyaute, Pazifik",
    "987":"LIM - Lima - J Chavez Int'l - Peru",
    "988":"NOP - Mactan Island - Nab - Philippines",
    "989":"MNL - Manila - Ninoy Aquino Int'l - Philippines",
    "990":"GDN - Gdansk - Poland",
    "991":"KRK - Krakau - Poland",
    "992":"POZ - Poznan, Lawica - Poland",
    "993":"SZZ - Stettin - Poland",
    "994":"WAW - Warsaw - Poland",
    "995":"FAO - Faro - Portugal",
    "996":"FNC - Funchal - Portugal",
    "997":"HOR - Horta - Portugal",
    "998":"LIS - Lisbon - Lisboa - Portugal",
    "999":"PDL - Ponta Delgada - Portugal",
    "1000":"OPO - Porto - Portugal",
    "1001":"PXO - Porto Santo - Portugal",
    "1002":"SMA - Santa Maria - Portugal",
    "1003":"TER - Terceira - Portugal",
    "1004":"BQN - Aguadilla - Puerto Rico",
    "1005":"MAZ - Mayaguez - Puerto Rico",
    "1006":"SJU - San Juan - Puerto Rico",
    "1007":"DOH - Doha - Qatar",
    "1008":"RUN - Saint Denis de la Reunion - Reunion",
    "1009":"BUH - Bucharest - Romania",
    "1010":"OTP - Bucharest, Otopeni - Romania",
    "1011":"CND - Constanza - Romania",
    "1012":"AER - Adler/Sochi - Russia",
    "1013":"KHV - Chabarovsk (Khabarovsk) - Russia",
    "1014":"HTA - Chita (Tschita) - Russia",
    "1015":"IKT - Irkutsk - Russia",
    "1016":"KZN - Kazan (Ka San) - Russia",
    "1017":"MRV - Mineralnye Vody - Russia",
    "1018":"DME - Moscow - Domodedovo - Russia",
    "1019":"MOW - Moscow - Metropolitan Area - Russia",
    "1020":"SVO - Moscow - Sheremetyevo - Russia",
    "1021":"VKO - Moscow - Vnukovo - Russia",
    "1022":"MMK - Murmansk - Russia",
    "1023":"OVB - Novosibirsk - Tolmachevo - Russia",
    "1024":"LED - St. Petersburg (Leningrad) - Pulkovo - Russia",
    "1025":"UUD - Ulan-Ude - Russia",
    "1026":"VLU - Velikiye Luki (Welikije Luki) - Russia",
    "1027":"ARH - Arkhangelsk - Russian Federation",
    "1028":"YKS - Yakutsk - Russian Federation",
    "1029":"KGL - Kigali - Gregoire Kayibanda - Rwanda",
    "1030":"APW - Apia - Samoa",
    "1031":"TMS - Sao Tome - Sao Tome Principe",
    "1032":"DHA - Dhahran - Saudi Arabia",
    "1033":"JED - Jeddah - King Abdulaziz Int'l - Saudi Arabia",
    "1034":"AHB - Khamis Mushayat - Saudi Arabia",
    "1035":"MED - Madinah, Mohammad Bin Abdulaziz - Saudi Arabia",
    "1036":"MED - Medina - Saudi Arabia",
    "1037":"RUH - Riyadh - King Khaled Int'l - Saudi Arabia",
    "1038":"TUU - Tabuk - Saudi Arabia",
    "1039":"TIF - Taif - Saudi Arabia",
    "1040":"YNB - Yanbu - Saudi Arabia",
    "1041":"DMM - Dammam, King Fahad Int'l - Saudi Arabia",
    "1042":"DKR - Dakar - Senegal",
    "1043":"SEZ - Mahe - Seychelles Int'l - Seychelles",
    "1044":"FNA - Freetown - Sierra Leone",
    "1045":"SIN - Singapore - Changi - Singapore",
    "1046":"QPG - Singapore - Paya Lebar - Singapore",
    "1047":"BTS - Bratislava - Slovakia",
    "1048":"LJU - Ljubljana - Brnik - Slovenia",
    "1049":"MBX - Maribor - Slovenia",
    "1050":"GSI - Guadalcanal - Solomon Islands",
    "1051":"HIR - Honiara Henderson Int'l - Solomon Islands",
    "1052":"MGQ - Mogadischu - Somalia",
    "1053":"AGZ - Aggeneys - South Africa",
    "1054":"ALJ - Alexander Bay - South Africa",
    "1055":"ADY - Alldays - South Africa",
    "1056":"BFN - Bloemfontein - South Africa",
    "1057":"CPT - Cape Town - South Africa",
    "1058":"DUR - Durban - South Africa",
    "1059":"ELS - East London - South Africa",
    "1060":"ELL - Ellisras - South Africa",
    "1061":"GRJ - George - South Africa",
    "1062":"JNB - Johannesburg - Johannesburg Int'l - South Africa",
    "1063":"KIM - Kimberley - South Africa",
    "1064":"KLZ - Kleinsee - South Africa",
    "1065":"HLA - Lanseria - South Africa",
    "1066":"LUJ - Lusisiki - South Africa",
    "1067":"MGH - Margate - South Africa",
    "1068":"MEZ - Messina - South Africa",
    "1069":"MBM - Mkambati - South Africa",
    "1070":"MZF - Mzamba - South Africa",
    "1071":"NLP - Nelspruit - South Africa",
    "1072":"MQP - Nelspruit - Kruger Mpumalanga Int'l Airport - South Africa",
    "1073":"NCS - Newcastle - South Africa",
    "1074":"OUH - Oudtshoorn - South Africa",
    "1075":"PHW - Phalaborwa - South Africa",
    "1076":"PZB - Pietermaritzburg - South Africa",
    "1077":"PTG - Pietersburg - South Africa",
    "1078":"NTY - Pilanesberg/Sun City - South Africa",
    "1079":"PBZ - Plettenberg Bay - South Africa",
    "1080":"PLZ - Port Elizabeth - South Africa",
    "1081":"PRY - Pretoria - Wonderboom Apt. - South Africa",
    "1082":"RCB - Richards Bay - South Africa",
    "1083":"SIS - Sishen - South Africa",
    "1084":"SZK - Skukuza - South Africa",
    "1085":"SBU - Springbok - South Africa",
    "1086":"TCU - Thaba'Nchu - South Africa",
    "1087":"ULD - Ulundi - South Africa",
    "1088":"UTT - Umtata - South Africa",
    "1089":"UTN - Upington - South Africa",
    "1090":"VYD - Vryheid - South Africa",
    "1091":"WVB - Walvis Bay - South Africa",
    "1092":"WEL - Welkom - South Africa",
    "1093":"ICN - Incheon, Incheon Int'l Airport - South Korea",
    "1094":"PUS - Pu San (Pusan) - Kimhae - South Korea",
    "1095":"ICN - Seoul - Incheon Int'l Airport - South Korea",
    "1096":"SEL - Seoul - Kimpo - South Korea",
    "1097":"ALC - Alicante - Spain",
    "1098":"LEI - Almeria - Spain",
    "1099":"ACE - Arrecife/Lanzarote - Spain",
    "1100":"BJZ - Badajoz - Spain",
    "1101":"BCN - Barcelona - Spain",
    "1102":"BIO - Bilbao - Spain",
    "1103":"ODB - Cordoba - Spain",
    "1104":"FUE - Fuerteventura - Spain",
    "1105":"GRO - Gerona - Spain",
    "1106":"GRX - Granada - Spain",
    "1107":"XRY - Jerez de la Frontera/Cadiz - Spain",
    "1108":"IBZ - Ibiza - Ibiza/Spain",
    "1109":"LCG - La Coruna - Spain",
    "1110":"LPA - Las Palmas - Spain",
    "1111":"MAD - Madrid - Barajas - Spain",
    "1112":"MAH - Mahon - Spain",
    "1113":"AGP - Malaga - Spain",
    "1114":"MJV - Murcia - Spain",
    "1115":"OVD - Oviedo - Spain",
    "1116":"PMI - Palma de Mallorca - Spain",
    "1117":"REU - Reus - Spain",
    "1118":"EAS - San Sebastian - Spain",
    "1119":"SPC - Santa Cruz de la Palma - Spain",
    "1120":"SDR - Santander - Spain",
    "1121":"SCQ - Santiago de Compostela - Spain",
    "1122":"SVQ - Sevilla - Spain",
    "1123":"TCI - Tenerife - Spain",
    "1124":"TFN - Tenerife - Norte Los Rodeos - Spain",
    "1125":"TFS - Tenerife - Sur Reina Sofia - Spain",
    "1126":"VLC - Valencia - Spain",
    "1127":"VLL - Valladolid - Spain",
    "1128":"VDE - Valverde - Spain",
    "1129":"VGO - Vigo - Spain",
    "1130":"VIT - Vitoria - Spain",
    "1131":"ZAZ - Zaragoza - Spain",
    "1132":"TFN - Los Rodeos - Teneriffa/Spain",
    "1133":"TFS - Reina Sofia - Teneriffa/Spain",
    "1134":"CMB - Colombo - Sri Lanka",
    "1135":"SKB - St. Kitts - St. Kitts And Nevis",
    "1136":"UVF - St. Lucia Hewanorra - St. Lucia",
    "1137":"SLU - St. Lucia Vigle - St. Lucia",
    "1138":"SFG - St. Martin - St. Martin",
    "1139":"KSL - Kassala - Sudan",
    "1140":"KRT - Khartoum - Sudan",
    "1141":"PBM - Paramaribo - Zanderij Int'l - Suriname",
    "1142":"MTS - Manzini - Matsapha Int'l - Swaziland",
    "1143":"KLR - Kalmar - Sweden",
    "1144":"KSD - Karlstad - Sweden",
    "1145":"KRN - Kiruna - Sweden",
    "1146":"KID - Kristianstad - Sweden",
    "1147":"LLA - Lulea - Sweden",
    "1148":"MMA - Malmo (Malmoe) - Sweden",
    "1149":"MMX - Malmo (Malmoe) - Sturup - Sweden",
    "1150":"ARN - Stockholm - Arlanda - Sweden",
    "1151":"BMA - Stockholm - Bromma - Sweden",
    "1152":"STO - Stockholm Metropolitan Area - Sweden",
    "1153":"SDL - Sundsvall - Sweden",
    "1154":"VXO - Vaexjoe - Sweden",
    "1155":"VST - Vasteras - Sweden",
    "1156":"ACH - Altenrhein - Switzerland",
    "1157":"BSL - Basel - Switzerland",
    "1158":"BRN - Bern - Switzerland",
    "1159":"ZDJ - Bern - Switzerland",
    "1160":"GVA - Geneva - Switzerland",
    "1161":"LUG - Lugano - Switzerland",
    "1162":"ZRH - Zurich (Zurich) - Kloten - Switzerland",
    "1163":"EAP - Basel/Mulhouse - Switzerland/France",
    "1164":"ALP - Aleppo - Syria",
    "1165":"DAM - Damascus, International - Syria",
    "1166":"DYU - Dushanbe (Duschanbe) - Tadschikistan",
    "1167":"KHH - Kaohsiung Int'l - Taiwan",
    "1168":"MZG - Makung - Taiwan",
    "1169":"TPE - Taipei - Chiang Kai Shek - Taiwan",
    "1170":"TAY - Taipei - Sung Shan - Taiwan",
    "1171":"ARK - Arusha - Tanzania",
    "1172":"DAR - Dar es Salam (Daressalam) - Tanzania",
    "1173":"JRO - Kilimadjaro - Tanzania",
    "1174":"BKK - Bangkok - Thailand",
    "1175":"CNX - Chiang Mai - Thailand",
    "1176":"HDY - Hatyai (Hat Yai) - Thailand",
    "1177":"PYX - Pattaya - Thailand",
    "1178":"HKT - Phuket - Thailand",
    "1179":"UTP - Utapao (Pattaya) - Thailand",
    "1180":"TAB - Tobago - Tobago",
    "1181":"TBU - Nuku'alofa - Fua'Amotu International - Tonga",
    "1182":"POS - Port of Spain - Trinidad",
    "1183":"DJE - Djerba - Tunisia",
    "1184":"MIR - Monastir - Tunisia",
    "1185":"SFA - Sfax - Tunisia",
    "1186":"TUN - Tunis - Carthage - Tunisia",
    "1187":"ADA - Adana - Turkey",
    "1188":"ANK - Ankara - Turkey",
    "1189":"AYT - Antalya - Turkey",
    "1190":"DLM - Dalaman - Turkey",
    "1191":"IST - Istanbul - Ataturk - Turkey",
    "1192":"ASB - Ashgabat, Ashkhabat - Turkmenistan",
    "1193":"EBB - Entebbe - Uganda",
    "1194":"ULU - Gulu - Uganda",
    "1195":"KBP - Kiev - Borispol - Ukraine",
    "1196":"IEV - Kiev - Zhulhany - Ukraine",
    "1197":"LWO - Lvov (Lwow, Lemberg) - Ukraine",
    "1198":"NLV - Nikolaev - Ukraine",
    "1199":"ODS - Odessa - Ukraine",
    "1200":"SIP - Simferopol - Ukraine",
    "1201":"AUH - Abu Dhabi - UAE",
    "1202":"FJR - Alfujairah (Fujairah) - UAE",
    "1203":"DXB - Dubai - UAE",
    "1204":"RKT - Ras al Khaymah (Ras al Khaimah) - UAE",
    "1205":"SHJ - Sharjah - UAE",
    "1206":"AAN - Al Ain - United Arab Emirates",
    "1207":"FJR - Fujairah, Int'l Airport - United Arab Emirates",
    "1208":"DCS - Doncaster, Robin Hood Int'l Airport - United Kingdom",
    "1209":"SZD - Sheffield, City Airport - United Kingdom",
    "1210":"DCS - Sheffield, Doncaster, Robin Hood Int'l Airport - United Kingdom",
    "1211":"ABZ - Aberdeen - United Kingdom",
    "1212":"BHD - Belfast - Harbour - United Kingdom",
    "1213":"BFS - Belfast International - United Kingdom",
    "1214":"BHX - Birmingham - United Kingdom",
    "1215":"CBG - Cambrigde - United Kingdom",
    "1216":"CWL - Cardiff - United Kingdom",
    "1217":"EMA - Derby (East Midlands) - United Kingdom",
    "1218":"GLA - Glasgow - United Kingdom",
    "1219":"PIK - Glasgow, Prestwick - United Kingdom",
    "1220":"IOM - Isle of Man - United Kingdom",
    "1221":"LBA - Leeds/Bradford - United Kingdom",
    "1222":"LCY - London - City Airport - United Kingdom",
    "1223":"LGW - London - Gatwick - United Kingdom",
    "1224":"LHR - London - Heathrow - United Kingdom",
    "1225":"STN - London - Stansted - United Kingdom",
    "1226":"MAN - Manchester - United Kingdom",
    "1227":"NCL - Newcastle - United Kingdom",
    "1228":"SOU - Southampton - Eastleigh - United Kingdom",
    "1229":"STN - Stansted (London) - United Kingdom",
    "1230":"SYY - Stornway - United Kingdom",
    "1231":"LSI - Sumburgh (Shetland) - United Kingdom",
    "1232":"MME - Teesside, Durham Tees Valley - United Kingdom",
    "1233":"MVD - Montevideo - Carrasco - Uruguay",
    "1234":"ABR - Aberdeen, SD - USA",
    "1235":"ABI - Abilene, TX - USA",
    "1236":"CAK - Akron, OH - USA",
    "1237":"ABY - Albany, GA - USA",
    "1238":"ALB - Albany, NY - USA",
    "1239":"ABQ - Albuquerque, NM - USA",
    "1240":"ESF - Alexandria, La - USA",
    "1241":"ABE - Allentown, PA - USA",
    "1242":"AOO - Altoona, PA - USA",
    "1243":"AMA - Amarillo, TX - USA",
    "1244":"ANC - Anchorage, AK - USA",
    "1245":"ARB - Ann Arbor, MI - USA",
    "1246":"ANB - Anniston, AL - USA",
    "1247":"ATW - Appelton/Neenah/Menasha, WI - USA",
    "1248":"AVL - Asheville, NC - USA",
    "1249":"ASE - Aspen Snowmass, CO - USA",
    "1250":"AHN - Athens, GA - USA",
    "1251":"ATO - Athens, OH - USA",
    "1252":"ATL - Atlanta, Hartsfield Atlanta Int'l Airport - USA",
    "1253":"ACY - Atlantic City, NJ - USA",
    "1254":"AGS - Augusta, GA - USA",
    "1255":"AUG - Augusta, ME - USA",
    "1256":"AUS - Austin, TX - USA",
    "1257":"BFL - Bakersfield, CA - USA",
    "1258":"BWI - Baltimore Washington Int'l Airport; MD - USA",
    "1259":"BGR - Bangor, ME - USA",
    "1260":"BTR - Baton Rouge, La - USA",
    "1261":"BPT - Beaumont/Pt. Arthur, TX - USA",
    "1262":"BKW - Beckley, WV - USA",
    "1263":"BLI - Bellingham, WA - USA",
    "1264":"BJI - Bemidji, MN - USA",
    "1265":"BEH - Benton Harbour, MI - USA",
    "1266":"BET - Bethel, AK - USA",
    "1267":"BIL - Billings, MT - USA",
    "1268":"BHM - Birmingham, AL - USA",
    "1269":"BIS - Bismarck/Mandan, ND - USA",
    "1270":"BMI - Bloomington, IL - USA",
    "1271":"BMG - Bloomington, IN - USA",
    "1272":"BLF - Bluefield, WV - USA",
    "1273":"BOI - Boise, ID - USA",
    "1274":"BXS - Borrego Springs, CA - USA",
    "1275":"BOS - Boston - Logan, MA - USA",
    "1276":"BZN - Bozeman, MT - USA",
    "1277":"BFD - Bradford/Warren, PA/Olean, NY - USA",
    "1278":"BRD - Brainerd, MN - USA",
    "1279":"BDR - Bridgeport, CT - USA",
    "1280":"BKX - Brookings, SD - USA",
    "1281":"BQK - Brunswick, GA - USA",
    "1282":"BUF - Buffalo/Niagara Falls, NY - USA",
    "1283":"BHC - Bullhead City, NV - USA",
    "1284":"BUR - Burbank, CA - USA",
    "1285":"BRL - Burlington, IA - USA",
    "1286":"BTV - Burlington, VT - USA",
    "1287":"BTM - Butte, MT - USA",
    "1288":"CLD - Carlsbad, CA - USA",
    "1289":"CPR - Casper, WY - USA",
    "1290":"CDC - Cedar City, UT - USA",
    "1291":"CID - Cedar Rapids, IA - USA",
    "1292":"CMI - Champaign, IL - USA",
    "1293":"CHS - Charleston, SC - USA",
    "1294":"CRW - Charleston, WV - USA",
    "1295":"CLT - Charlotte, NC - USA",
    "1296":"CHO - Charlottesville, VA - USA",
    "1297":"CHA - Chattanooga, TN - USA",
    "1298":"CYS - Cheyenne, WY - USA",
    "1299":"ORD - Chicago O'Hare Int'l Airport, IL - USA",
    "1300":"CHI - Chicago, IL - USA",
    "1301":"MDW - Chicago, Midway, IL - USA",
    "1302":"CIC - Chico, CA - USA",
    "1303":"CVG - Cincinnati, OH - USA",
    "1304":"CKB - Clarksburg, WV - USA",
    "1305":"BKL - Cleveland, Burke Lakefront, OH - USA",
    "1306":"CLE - Cleveland, Hopkins, OH - USA",
    "1307":"COD - Cody/Powell/Yellowstone, WY - USA",
    "1308":"KCC - Coffmann Cove, AK - USA",
    "1309":"CLL - College Station/Bryan, TX - USA",
    "1310":"COS - Colorado Springs, CO - USA",
    "1311":"CAE - Columbia, SC - USA",
    "1312":"CSG - Columbus, GA - USA",
    "1313":"CMH - Columbus, OH - USA",
    "1314":"CCR - Concord, CA - USA",
    "1315":"CDV - Cordova, AK - USA",
    "1316":"CRP - Corpus Christi, TX - USA",
    "1317":"CGA - Craig, AK - USA",
    "1318":"CEC - Crescent City, CA - USA",
    "1319":"DAL - Dallas, Love Field, TX - USA",
    "1320":"DFW - Dallas/Ft. Worth, TX - USA",
    "1321":"DAN - Danville, VA - USA",
    "1322":"DAY - Dayton, OH - USA",
    "1323":"DAB - Daytona Beach, FL - USA",
    "1324":"DEC - Decatur, IL - USA",
    "1325":"DEN - Denver International Airport, CO - USA",
    "1326":"DSM - Des Moines, IA - USA",
    "1327":"DET - Detroit City, MI - USA",
    "1328":"DTT - Detroit Metropolitan Area, MI - USA",
    "1329":"DTW - Detroit Metropolitan Wayne County Airport, MI - USA",
    "1330":"DVL - Devils Lake, ND - USA",
    "1331":"DLG - Dillingham, AK - USA",
    "1332":"DHN - Dothan, AL - USA",
    "1333":"DUJ - Dubois, PA - USA",
    "1334":"DBQ - Dubuque, IA - USA",
    "1335":"DLH - Duluth, MN/Superior, WI - USA",
    "1336":"DRO - Durango, CO - USA",
    "1337":"DUT - Dutch Harbor, AK - USA",
    "1338":"EAU - Eau Clarie, WI - USA",
    "1339":"ELP - El Paso, TX - USA",
    "1340":"EKI - Elkhart, IN - USA",
    "1341":"EKO - Elko, NV - USA",
    "1342":"ELM - Elmira, NY - USA",
    "1343":"ELY - Ely, NV - USA",
    "1344":"ERI - Erie, PA - USA",
    "1345":"ESC - Escabana, MI - USA",
    "1346":"EUG - Eugene, OR - USA",
    "1347":"ACV - Eureka, CA - USA",
    "1348":"EVV - Evansville, IN - USA",
    "1349":"FAI - Fairbanks, AK - USA",
    "1350":"FAR - Fargo, ND, MN - USA",
    "1351":"FMN - Farmington, NM - USA",
    "1352":"FYV - Fayetteville, AR - USA",
    "1353":"FAY - Fayetteville/Ft. Bragg, NC - USA",
    "1354":"FLG - Flagstaff, AZ - USA",
    "1355":"FNT - Flint, MI - USA",
    "1356":"FLO - Florence, SC - USA",
    "1357":"FOD - Fort Dodge, IA - USA",
    "1358":"FHU - Fort Huachuca/Sierra Vista, AZ - USA",
    "1359":"FLL - Fort Lauderdale/Hollywood, FL - USA",
    "1360":"FMY - Fort Myers, Metropolitan Area, FL - USA",
    "1361":"RSW - Fort Myers, Southwest Florida Reg, FL - USA",
    "1362":"FSM - Fort Smith, AR - USA",
    "1363":"VPS - Fort Walton Beach, FL - USA",
    "1364":"FWA - Fort Wayne, IN - USA",
    "1365":"FKL - Franklin/Oil City, PA - USA",
    "1366":"FAT - Fresno, CA - USA",
    "1367":"GAD - Gadsden, AL - USA",
    "1368":"GNV - Gainesville, FL - USA",
    "1369":"GCC - Gilette, WY - USA",
    "1370":"GGW - Glasgow, MT - USA",
    "1371":"GDV - Glendive, MT - USA",
    "1372":"GCN - Grand Canyon, AZ - USA",
    "1373":"GFK - Grand Forks, ND - USA",
    "1374":"GJT - Grand Junction, CO - USA",
    "1375":"GRR - Grand Rapids, MI - USA",
    "1376":"GPZ - Grand Rapids, MN - USA",
    "1377":"GTF - Great Falls, MT - USA",
    "1378":"GRB - Green Bay, WI - USA",
    "1379":"LWB - Greenbrier/Lewisburg, WV - USA",
    "1380":"GSO - Greensboro/Winston Salem, NC - USA",
    "1381":"GLH - Greenville, MS - USA",
    "1382":"PGV - Greenville, NC - USA",
    "1383":"GSP - Greenville/Spartanburg, SC - USA",
    "1384":"GON - Groton/New London, CT - USA",
    "1385":"GPT - Gulfport/Biloxi, MS - USA",
    "1386":"GUC - Gunnison/Crested Butte, CO - USA",
    "1387":"HNS - Haines, AK - USA",
    "1388":"CMX - Hancock, MI - USA",
    "1389":"HRL - Harlington/South Padre Island, TX - USA",
    "1390":"MDT - Harrisburg, PA - Harrisburg Int'l - USA",
    "1391":"HAR - Harrisburg, PA - Harrisburg Skyport - USA",
    "1392":"BDL - Hartford, CT/Springfield, MA - USA",
    "1393":"HVR - Havre, MT - USA",
    "1394":"HLN - Helena, MT - USA",
    "1395":"HIB - Hibbing, MN - USA",
    "1396":"HKY - Hickory, NC - USA",
    "1397":"ITO - Hilo, HI - USA",
    "1398":"HHH - Hilton Head Island, SC - USA",
    "1399":"HOM - Homer, AK - USA",
    "1400":"HNL - Honolulu, HI - USA",
    "1401":"HNH - Hoonah, AK - USA",
    "1402":"HOU - Houston, Hobby, TX - USA",
    "1403":"IAH - Houston, Intercontinental, TX - USA",
    "1404":"HTS - Huntington, OH - USA",
    "1405":"HSV - Huntsville, AL - USA",
    "1406":"HON - Huron, SD - USA",
    "1407":"HYA - Hyannis, MA - USA",
    "1408":"HYG - Hydaburg, AK - USA",
    "1409":"IDA - Idaho Falls, ID - USA",
    "1410":"ILI - Iliamna, AK - USA",
    "1411":"IPL - Imperial, CA - USA",
    "1412":"IND - Indianapolis, IN - USA",
    "1413":"INL - International Falls, MN - USA",
    "1414":"IYK - Inykern, CA - USA",
    "1415":"ITH - Ithaca/Cortland, NY - USA",
    "1416":"JAC - Jackson Hole, WY - USA",
    "1417":"JXN - Jackson, MI - USA",
    "1418":"JAN - Jackson, MS - USA",
    "1419":"MKL - Jackson, TN - USA",
    "1420":"JAX - Jacksonville, FL - USA",
    "1421":"OAJ - Jacksonville, NC - USA",
    "1422":"JMS - Jamestown, ND - USA",
    "1423":"JHW - Jamestown, NY - USA",
    "1424":"JST - Johnstown, PA - USA",
    "1425":"JLN - Joplin, MO - USA",
    "1426":"JNU - Juneau, AK - Juneau Int'l - USA",
    "1427":"OGG - Kahului, HI - USA",
    "1428":"AZO - Kalamazoo/Battle Creek, MI - USA",
    "1429":"FCA - Kalispell, MT - USA",
    "1430":"MUE - Kamuela, HI - USA",
    "1431":"MCI - Kansas City, MO - Int'l - USA",
    "1432":"JHM - Kapalua West, HI - USA",
    "1433":"MKK - Kaunakakai, HI - USA",
    "1434":"ENA - Kenai, AK - USA",
    "1435":"KTN - Ketchikan, AK - USA",
    "1436":"EYW - Key West, FL - USA",
    "1437":"ILE - Killeem, TX - USA",
    "1438":"AKN - King Salomon, AK - USA",
    "1439":"ISO - Kingston, NC - USA",
    "1440":"LMT - Klamath Fall, OR - USA",
    "1441":"KLW - Klawock, AK - USA",
    "1442":"TYS - Knoxville, TN - USA",
    "1443":"ADQ - Kodiak, AK - USA",
    "1444":"KOA - Kona, HI - USA",
    "1445":"OTZ - Kotzbue, AK - USA",
    "1446":"LSE - La Crosse, WI - USA",
    "1447":"WLB - Labouchere Bay, AK - USA",
    "1448":"LAF - Lafayette, IN - USA",
    "1449":"LFT - Lafayette, La - USA",
    "1450":"LCH - Lake Charles, La - USA",
    "1451":"HII - Lake Havasu City, AZ - USA",
    "1452":"TVL - Lake Tahoe, CA - USA",
    "1453":"LNY - Lanai City, HI - USA",
    "1454":"LNS - Lancaster, PA - USA",
    "1455":"LAN - Lansing, MI - USA",
    "1456":"LAR - Laramie, WY - USA",
    "1457":"LRD - Laredo, TX - USA",
    "1458":"LAS - Las Vegas, NV - USA",
    "1459":"LBE - Latrobe, PA - USA",
    "1460":"PIB - Laurel/Hattisburg, MS - USA",
    "1461":"LAW - Lawton, OK - USA",
    "1462":"LEB - Lebanon, NH - USA",
    "1463":"LWS - Lewiston, ID - USA",
    "1464":"LWT - Lewistown, MT - USA",
    "1465":"LEX - Lexington, KY - USA",
    "1466":"LIH - Lihue, HI - USA",
    "1467":"LNK - Lincoln, NE - USA",
    "1468":"LIT - Little Rock, AR - USA",
    "1469":"LGB - Long Beach, CA - USA",
    "1470":"LIJ - Long Island, AK - USA",
    "1471":"ISP - Long Island, Islip, NY - Mac Arthur - USA",
    "1472":"GGG - Longview/Kilgore, TX - USA",
    "1473":"LAX - Los Angeles, CA - Int'l - USA",
    "1474":"SDF - Louisville, KY - USA",
    "1475":"LBB - Lubbock, TX - USA",
    "1476":"LYH - Lynchburg, VA - USA",
    "1477":"MCN - Macon, GA - USA",
    "1478":"MSN - Madison, WI - USA",
    "1479":"MHT - Manchester, NH - USA",
    "1480":"MTH - Marathon, FL - USA",
    "1481":"MQT - Marquette, MI - USA",
    "1482":"MVY - Martha's Vineyard, MA - USA",
    "1483":"MCW - Mason City, IA - USA",
    "1484":"MTO - Mattoon, IL - USA",
    "1485":"MFE - McAllen, TX - USA",
    "1486":"MFR - Medford, OR - USA",
    "1487":"MLB - Melbourne, FL - USA",
    "1488":"MEM - Memphis, TN - USA",
    "1489":"MCE - Merced, CA - USA",
    "1490":"MEI - Meridian, MS - USA",
    "1491":"MTM - Metlakatla, AK - USA",
    "1492":"MIA - Miami, FL - USA",
    "1493":"MAF - Midland/Odessa, TX - USA",
    "1494":"MLS - Miles City, MT - USA",
    "1495":"MKE - Milwaukee, WI - USA",
    "1496":"MSP - Minneapolis - St. Paul Int'l Airport, MN - USA",
    "1497":"MOT - Minot, ND - USA",
    "1498":"MSO - Missula, MT - USA",
    "1499":"MHE - Mitchell, SD - USA",
    "1500":"MOB - Mobile, AL - Pascagoula, MS - USA",
    "1501":"MOD - Modesto, CA - USA",
    "1502":"MLI - Moline/Quad Cities, IL - USA",
    "1503":"MLU - Monroe, La - USA",
    "1504":"MRY - Monterey, CA - USA",
    "1505":"MGM - Montgomery, AL - USA",
    "1506":"MTJ - Montrose/Tellruide, CO - USA",
    "1507":"MGW - Morgantown, WV - USA",
    "1508":"MWH - Moses Lake, WA - USA",
    "1509":"MCL - Mt. McKinley, AK - USA",
    "1510":"MSL - Muscle Shoals, AL - USA",
    "1511":"MKG - Muskegon, MI - USA",
    "1512":"MYR - Myrtle Beach, SC - USA",
    "1513":"ACK - Nantucket, MA - USA",
    "1514":"APF - Naples, FL - USA",
    "1515":"BNA - Nashville, TN - USA",
    "1516":"EWN - New Bern, NC - USA",
    "1517":"HVN - New Haven, CT - USA",
    "1518":"MSY - New Orleans, La - USA",
    "1519":"JFK - New York - John F. Kennedy, NY - USA",
    "1520":"LGA - New York - La Guardia, NY - USA",
    "1521":"EWR - New York - Newark, NJ - USA",
    "1522":"NYC - New York, NY - USA",
    "1523":"SWF - Newburgh, NY - USA",
    "1524":"PHF - Newport News/Williamsburg, VA - USA",
    "1525":"IAG - Niagara Falls Int'l - USA",
    "1526":"OME - Nome, AK - USA",
    "1527":"ORF - Norfolk/Virginia Beach, VA - USA",
    "1528":"OTH - North Bend, OR - USA",
    "1529":"OAK - Oakland, CA - USA",
    "1530":"OKC - Oklahoma City, OK - Will Rogers World - USA",
    "1531":"OMA - Omaha, NE - USA",
    "1532":"ONT - Ontario, CA - USA",
    "1533":"SNA - Orange County (Santa Ana), CA - USA",
    "1534":"ORL - Orlando Metropolitan Area, FL - USA",
    "1535":"ORL - Orlando Int'l Airport, FL - USA",
    "1536":"OSH - Oshkosh, WI - USA",
    "1537":"OWB - Owensboro, KY - USA",
    "1538":"OXR - Oxnard, CA - USA",
    "1539":"PAH - Paducah, KY - USA",
    "1540":"PGA - Page/Lake Powell, AZ - USA",
    "1541":"PKB - Pakersburg, WV/Marietta, OH - USA",
    "1542":"PSP - Palm Springs, CA - USA",
    "1543":"PMD - Palmdale/Lancaster, CA - USA",
    "1544":"PFN - Panama City, FL - USA",
    "1545":"PSC - Pasco, WA - USA",
    "1546":"PLN - Pellston, MI - USA",
    "1547":"PDT - Pendelton, OR - USA",
    "1548":"PNS - Pensacola, FL - USA",
    "1549":"PIA - Peoria/Bloomington, IL - USA",
    "1550":"PSG - Petersburg, AK - USA",
    "1551":"PHL - Philadelphia, PA - Int'l - USA",
    "1552":"PHX - Phoenix, AZ - Sky Harbor Int'l - USA",
    "1553":"PIR - Pierre, SD - USA",
    "1554":"PIT - Pittsburgh Int'l Airport, PA - USA",
    "1555":"PLB - Plattsburgh, NY - USA",
    "1556":"PIH - Pocatello, ID - USA",
    "1557":"CLM - Port Angeles, WA - USA",
    "1558":"PDX - Portland Int'l, OR - USA",
    "1559":"PWM - Portland, ME - USA",
    "1560":"POU - Poughkeepsie, NY - USA",
    "1561":"PQI - Presque Island, ME - USA",
    "1562":"PVD - Providence, RI - USA",
    "1563":"SCC - Prudhoe Bay, AK - USA",
    "1564":"PUB - Pueblo, CO - USA",
    "1565":"PUW - Pullman, WA - USA",
    "1566":"UIN - Quincy, IL - USA",
    "1567":"RDU - Raleigh/Durham, NC - USA",
    "1568":"RAP - Rapid City, SD - USA",
    "1569":"RDG - Reading, PA - USA",
    "1570":"RDD - Redding, CA - USA",
    "1571":"RDM - Redmond, OR - USA",
    "1572":"RNO - Reno, NV - USA",
    "1573":"RHI - Rhinelander, WI - USA",
    "1574":"RIC - Richmond, VA - USA",
    "1575":"ROA - Roanoke, VA - USA",
    "1576":"RST - Rochester, MN - USA",
    "1577":"ROC - Rochester, NY - USA",
    "1578":"RKS - Rock Springs, WY - USA",
    "1579":"RFD - Rockford, IL - USA",
    "1580":"RKD - Rockland, ME - USA",
    "1581":"RWI - Rocky Mount - Wilson, NC - USA",
    "1582":"SMF - Sacramento, CA - USA",
    "1583":"MBS - Saginaw/Bay City/Midland, MI - USA",
    "1584":"SLE - Salem, OR - USA",
    "1585":"SNS - Salinas, CA - USA",
    "1586":"SBY - Salisbury, MD - USA",
    "1587":"SLC - Salt Lake City, UT - USA",
    "1588":"SJT - San Angelo, TX - USA",
    "1589":"SAT - San Antonio, TX - USA",
    "1590":"SAN - San Diego - Lindberg Field Int'l, CA - USA",
    "1591":"SFO - San Francisco - Int'l Airport, SA - USA",
    "1592":"SJC - San Jose, CA - USA",
    "1593":"SBP - San Luis Obisco, CA - USA",
    "1594":"SBA - Santa Barbara, CA - USA",
    "1595":"SMX - Santa Maria, CA - USA",
    "1596":"STS - Santa Rosa, CA - USA",
    "1597":"SRQ - Sarasota/Bradenton, FL - USA",
    "1598":"SAV - Savannah, GA - USA",
    "1599":"SCF - Scottsdale, AZ - USA",
    "1600":"SEA - Seattle/Tacoma, WA - USA",
    "1601":"SHD - Shenandoah Valley/Stauton, VA - USA",
    "1602":"SHR - Sheridan, WY - USA",
    "1603":"SHV - Shreveport, La - USA",
    "1604":"SDY - Sidney, MT - USA",
    "1605":"SUX - Sioux City, IA - USA",
    "1606":"FSD - Sioux Falls, SD - USA",
    "1607":"SIT - Sitka, AK - USA",
    "1608":"SGY - Skagway, AK - USA",
    "1609":"SBN - South Bend, IN - USA",
    "1610":"GEG - Spokane, WA - USA",
    "1611":"SPI - Springfield, IL - USA",
    "1612":"SGF - Springfield, MO - USA",
    "1613":"SGU - St. George, UT - USA",
    "1614":"STL - St. Louis - Lambert, MO - USA",
    "1615":"SCE - State College/Belefonte, PA - USA",
    "1616":"HDN - Steamboat Springs, CO - USA",
    "1617":"SCK - Stockton, CA - USA",
    "1618":"SUN - Sun Valley, ID - USA",
    "1619":"SYR - Syracuse, NY - USA",
    "1620":"TKA - Talkeetna, AK - USA",
    "1621":"TLH - Tallahassee, FL - USA",
    "1622":"TPA - Tampa Int'l, FL - USA",
    "1623":"TEX - Telluride, CO - USA",
    "1624":"HUF - Terre Haute, IN - USA",
    "1625":"TXK - Texarkana, AR - USA",
    "1626":"TVF - Thief River Falls, MN - USA",
    "1627":"KTB - Thorne Bay, AK - USA",
    "1628":"TOL - Toledo, OH - USA",
    "1629":"TVC - Traverse City, MI - USA",
    "1630":"TTN - Trenton/Princeton, NJ - USA",
    "1631":"TRI - Tri-Cities Regional, TN/VA - USA",
    "1632":"TUS - Tucson, AZ - USA",
    "1633":"TUP - Tulepo, MS - USA",
    "1634":"TUL - Tulsa, OK - USA",
    "1635":"TCL - Tuscaloosa, AL - USA",
    "1636":"TWF - Twin Falls, ID - USA",
    "1637":"TYR - Tyler, TX - USA",
    "1638":"UCA - Utica, NY - USA",
    "1639":"EGE - Vail, CO - USA",
    "1640":"VDZ - Valdez, AK - USA",
    "1641":"VLD - Valdosta, GA - USA",
    "1642":"VEL - Vernal, UT - USA",
    "1643":"VRB - Vero Beach/Ft. Pierce, FL - USA",
    "1644":"VIS - Visalia, CA - USA",
    "1645":"ACT - Waco, TX - USA",
    "1646":"ALW - Walla Walla, WA - USA",
    "1647":"BWI - Washington DC - Baltimore Washington Int'l - USA",
    "1648":"IAD - Washington DC - Dulles Int'l - USA",
    "1649":"DCA - Washington DC - Ronald Reagan National - USA",
    "1650":"WAS - Washington, DC - USA",
    "1651":"ALO - Waterloo, IA - USA",
    "1652":"ATY - Watertown, SD - USA",
    "1653":"CWA - Wausau/Stevens Point, WI - USA",
    "1654":"EAT - Wenatchee, WA - USA",
    "1655":"PBI - West Palm Beach, FL - USA",
    "1656":"WYS - West Yellowstone, MT - USA",
    "1657":"HPN - White Plains, NY - USA",
    "1658":"SPS - Wichita Falls, TX - USA",
    "1659":"ICT - Wichita, KS - USA",
    "1660":"AVP - Wilkes Barre/Scranton, PA - USA",
    "1661":"IPT - Williamsport, PA - USA",
    "1662":"ISL - Williston, ND - USA",
    "1663":"ILM - Wilmington, NC - USA",
    "1664":"OLF - Wolf Point, MT - USA",
    "1665":"ORH - Worcester, MA - USA",
    "1666":"WRL - Worland, WY - USA",
    "1667":"WRG - Wrangell, AK - USA",
    "1668":"YKM - Yakima, WA - USA",
    "1669":"YAK - Yakutat, AK - USA",
    "1670":"YUM - Yuma, AZ - USA",
    "1671":"SKD - Samarkand - Uzbekistan",
    "1672":"TAS - Tashkent - Vostochny - Uzbekistan",
    "1673":"TMZ - Termez (Termes) - Uzbekistan",
    "1674":"VLI - Port Vila - Vanuatu",
    "1675":"SON - Santo - Vanuatu",
    "1676":"BLA - Barcelona - Venezuela",
    "1677":"CCS - Caracas - Venezuela",
    "1678":"MAR - Maracaibo - La Chinita - Venezuela",
    "1679":"PMV - Margerita - Venezuela",
    "1680":"PZO - Puerto Ordaz - Venezuela",
    "1681":"VLN - Valencia - Venezuela",
    "1682":"HAN - Hanoi - Noibai - Viet Nam",
    "1683":"SGN - Ho Chi Minh City (Saigon) - Viet Nam",
    "1684":"HUI - Hue - Phu Bai - Viet Nam",
    "1685":"SGN - Saigon (Ho Chi Minh City) - Viet Nam",
    "1686":"STX - St. Croix - Virgin Islands",
    "1687":"STT - St. Thomas - Virgin Islands",
    "1688":"EIS - Tortola - Virgin Islands",
    "1689":"VIJ - Virgin Gorda - Virgin Islands",
    "1690":"EIS - Beef Island - Virgin Islands, British",
    "1691":"FUT - Futuna - Wallis and Futuna Islands",
    "1692":"WLS - Wallis - Wallis and Futuna Islands",
    "1693":"ADE - Aden - Yemen",
    "1694":"SAH - Sanaa (Sana'a) - Sana'a International - Yemen",
    "1695":"BEG - Belgrad (Beograd) - Yugoslavia",
    "1696":"INI - Nis - Yugoslavia",
    "1697":"QND - Novi Sad - Yugoslavia",
    "1698":"TGD - Podgorica - Yugoslavia",
    "1699":"PRN - Pristina - Yugoslavia",
    "1700":"TIV - Tivat - Yugoslavia",
    "1701":"FKI - Kisangani - Zaire",
    "1702":"FBM - Lumbumbashi - Zaire",
    "1703":"CIP - Chipata - Zambia",
    "1704":"KIW - Kitwe - Zambia",
    "1705":"LUN - Lusaka - Zambia",
    "1706":"MFU - Mfuwe - Zambia",
    "1707":"NLA - N'Dola - Zambia",
    "1708":"BFO - Buffalo Range - Zimbabwe",
    "1709":"BUQ - Bulawayo - Zimbabwe",
    "1710":"GWE - Gweru - Zimbabwe",
    "1711":"HRE - Harare - Zimbabwe",
    "1712":"HWN - Hwange National Park - Zimbabwe",
    "1713":"MVZ - Masvingo - Zimbabwe",
    "1714":"SAY - Salisbury - Zimbabwe",
    "1715":"VFA - Victoria Falls - Zimbabwe"
    }

  export  const airportsOptions = Object.keys(airports).map(key=>{
    return {label: airports[key], value: key}
  })